import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import SlateMobile from "@/components/slateMobile";
import SlateReact from "@/components/slateReact";
import PlainTextExample from "@/components/plainText";
import { useBearStore, useAuthStore } from "@/globals/authStorage";
import { Slate } from "slate-react";
import CheckListsExample from "@/components/checkListExample";
export default function Home() {
	return (
		<div className="m-8 main-wrapper">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			{/* <SlateMobile /> */}
			<SlateReact />


			{/* <PlainTextExample /> */}
		</div>
	);
}
